---
- hosts: all
  handlers:
    - name: Enable nginx
      become: yes
      become_user: root
      service: name=nginx enabled=yes
    - name: Restart nginx
      become: yes
      become_user: root
      service: name=nginx state=restarted

  tasks:
    - name: install the EPEL release rpm 
      become: yes
      become_user: root
      yum:
        name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: What about nginx
      become: yes
      become_user: root
      yum:
        name: nginx
        state: latest

    - name: Copy index.html
      become: yes
      become_user: root
      template: src=./index.html dest=/usr/share/nginx/html/index.html
      notify:
        - Enable nginx
        - Restart nginx


