# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 config.vm.box_check_update = "false"
 config.vm.provider "virtualbox" do |vb|
   vb.memory = "1024"
 end

 config.vm.define "centos7test" do |mybox|
   mybox.vm.hostname = "centos7test"
   mybox.vm.box = "geerlingguy/centos7"
   mybox.vm.network :private_network, ip: "192.168.10.10"
   mybox.vm.network "forwarded_port", guest: "80", host: "8080"
   mybox.vm.provision "ansible" do |ansible|
     ansible.playbook="hello-playbook.yaml"
   end
  end
end
