---
- hosts: loadbalancer
  gather_facts: false
  tasks:
    - service: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: webstatic
  gather_facts: false
  tasks:
    - service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped

- hosts: webapp
  gather_facts: false
  tasks:
    - service: name=apache2 state=stopped
    - wait_for: port=80 state=stopped

- hosts: database
  gather_facts: false
  tasks:
    - service: name=mysql state=restarted
    - wait_for: port=3306 state=started

- hosts: webstatic
  gather_facts: false
  tasks:
    - service: name=apache2 state=started
    - wait_for: port=80 state=started

- hosts: webapp
  gather_facts: false
  tasks:
    - service: name=apache2 state=started
    - wait_for: port=80 state=started

- hosts: loadbalancer
  gather_facts: false
  tasks:
    - service: name=nginx state=started
    - wait_for: port=80 state=started
